# All habitats in Pokémon Pokopia from Serebii
# Auto-generated by scrape.py — do not edit manually

HABITATS = [
  {
    "id": 1,
    "name": "Picture",
    "description": "Description"
  },
  {
    "id": 1,
    "name": "#001",
    "description": "Four tufts of tall grass bunched together in a plot. The perfect hiding place for small Pokémon"
  },
  {
    "id": 2,
    "name": "#002",
    "description": "Shaded tall grass that stays cool, even in the midday sun. Pokémon might stop by to relax"
  },
  {
    "id": 3,
    "name": "#003",
    "description": "tall grass near a large boulder. Perfect for hide-and-seek"
  },
  {
    "id": 4,
    "name": "#004",
    "description": "Tall grass along the water's edge. A habitat thriving with energy thanks to an abundance of water"
  },
  {
    "id": 5,
    "name": "#005",
    "description": "Tall grass that stands firm against the spray of saltwater. Good for escaping the seaside heat"
  },
  {
    "id": 6,
    "name": "#006",
    "description": "Such a high elevation means this area is quite cool. The wind blows all the way through the tall grass"
  },
  {
    "id": 7,
    "name": "#007",
    "description": "A gently lit plot of tall grass. Pokémon are drawn to the inviting light"
  },
  {
    "id": 8,
    "name": "#008",
    "description": "A beautiful bed of wildflowers. A faint, sweet aroma wafts about it."
  },
  {
    "id": 9,
    "name": "#009",
    "description": "Beautifully blooming flowers beneath the shade ofa tree. Pokémon are attracted by the damp scent"
  },
  {
    "id": 10,
    "name": "#010",
    "description": "A field of blooming waterside flowers. Pokémon may be attracted by the aroma and clear water."
  },
  {
    "id": 11,
    "name": "#011",
    "description": "A large field of flowers. Every petal emanates an ambrosial aroma"
  },
  {
    "id": 12,
    "name": "#012",
    "description": "A bed of flowers blooming at high elevation. The wind carries their sweet aroma all around"
  },
  {
    "id": 13,
    "name": "#013",
    "description": "A habitat that exudes a gentle elegance. Pokémon could rest in joyful peace here"
  },
  {
    "id": 14,
    "name": "#014",
    "description": "Plant some hedges near blooming flowers, and you'll have a decent garden in no time flat"
  },
  {
    "id": 15,
    "name": "#015",
    "description": "Vegetables growing in a nice, wild field. Seems likely to attact Pokémon who enjoy farming"
  },
  {
    "id": 16,
    "name": "#016",
    "description": "The warm air from three campfires rises high into the sky!"
  },
  {
    "id": 17,
    "name": "#017",
    "description": "A campsite that celebrates elements of nature. Pokémon warm themselves in front of the campfire"
  },
  {
    "id": 18,
    "name": "#018",
    "description": "Pokémon who like to train may come here to sit under the waterfall and tone their bodies"
  },
  {
    "id": 19,
    "name": "#019",
    "description": "A table set with dishes-and a chair for sitting. Hungry Pokémon might swing by here.."
  },
  {
    "id": 20,
    "name": "#020",
    "description": "A basked placed atop a table is all it takes to feel a little picnicky"
  },
  {
    "id": 21,
    "name": "#021",
    "description": "A flower vase placed on top of a table. Pokémon might sit on the chair to look at the flower."
  },
  {
    "id": 22,
    "name": "#022",
    "description": "A bench near some hedges. Pokémon can rest here and bask in nature"
  },
  {
    "id": 23,
    "name": "#023",
    "description": "A bench illuminated by gentle light. Pokémon entranced by the light might stop by"
  },
  {
    "id": 24,
    "name": "#024",
    "description": "After a fierce training session, Pokémon can rest their tired bodies on this bench"
  },
  {
    "id": 25,
    "name": "#025",
    "description": "When injured, seek first aid immediately! Pokémon skilled at healing may come to this habitat."
  },
  {
    "id": 26,
    "name": "#026",
    "description": "A first-aid kit is on hand in case any Pokémon injure themselves exercising"
  },
  {
    "id": 27,
    "name": "#027",
    "description": "A solitary sign by the middle of the road. Pokémon might head in the arrow's direction"
  },
  {
    "id": 28,
    "name": "#028",
    "description": "This long, wide cart can fit two large crates"
  },
  {
    "id": 29,
    "name": "#029",
    "description": "Haul logs with the cart and split them on the tree stump. The chair is there for taking breaks"
  },
  {
    "id": 30,
    "name": "#030",
    "description": "A bed with a cute doll. Small Pokémon would probably feel safe sleeping here"
  },
  {
    "id": 31,
    "name": "#031",
    "description": "A bed bathed in gentle light. Pokémon could probably sleep peacefully here"
  },
  {
    "id": 32,
    "name": "#032",
    "description": "Candles and plated food placed silently before a gravestone. Pretty creepyâ¦"
  },
  {
    "id": 33,
    "name": "#033",
    "description": "Light the candles by the gravestone to add some swaying blue flames for double the eeriness"
  },
  {
    "id": 34,
    "name": "#034",
    "description": "A peaceful, refreshing spot to take a break while Chansey watches over you"
  },
  {
    "id": 35,
    "name": "#035",
    "description": "Pokémon may be lured here by the glow of the mushroom and the scent of the plant-shaped pot"
  },
  {
    "id": 36,
    "name": "#036",
    "description": "Have fun on the inflatable boat! If you get tired, you can take a break under the umbrella"
  },
  {
    "id": 37,
    "name": "#037",
    "description": "A strange smooth rock has drained the vitality from this tall grass"
  },
  {
    "id": 38,
    "name": "#038",
    "description": "The large machine doesn't seem to work, even if you plug in the cords and hit the buttons"
  },
  {
    "id": 39,
    "name": "#039",
    "description": "Bird Pokémon can lounge in the birdhouse after enjoying a meal of various berries"
  },
  {
    "id": 40,
    "name": "#040",
    "description": "A cozy campfire underneat a clear sky. Prepare a big feast and have a good time!"
  },
  {
    "id": 41,
    "name": "#041",
    "description": "Reminders of rain and a plate for offering food. The perfect spot to call for rainy weather"
  },
  {
    "id": 42,
    "name": "#042",
    "description": "Reminders of sunshine and a plate for offering food. This is the perfect spot to call for fair weather"
  },
  {
    "id": 43,
    "name": "#043",
    "description": "It may look like a bunch of junk, but every single piece here is worthy of study to a professor"
  },
  {
    "id": 44,
    "name": "#044",
    "description": "This space is packed with wooden furniture. It feels almost like you're in a mountain cabin"
  },
  {
    "id": 45,
    "name": "#045",
    "description": "A berry table, a berry bedâ¦Everything's a berry! Just looking at them makes you hungry"
  },
  {
    "id": 46,
    "name": "#046",
    "description": "Take a breather in a garden chair while looking at softly lit flowers"
  },
  {
    "id": 47,
    "name": "#047",
    "description": "Pokémon might come here mistakenly thinking that this is an actual sleeping Snorlax!"
  },
  {
    "id": 48,
    "name": "#048",
    "description": "Enjoy the retro vibe of this collection of wonderful antique furniture!"
  },
  {
    "id": 49,
    "name": "#049",
    "description": "All Poké Ballsâ¦or so you thought! Living here is oddly comforting somehow"
  },
  {
    "id": 50,
    "name": "#050",
    "description": "A small plot made up of four tufts of yellow tall grass. Spots like this are often found in harbor towns"
  },
  {
    "id": 51,
    "name": "#051",
    "description": "Yellow tall grass in the shade of a tree. The habitat has a melancholy feel to it."
  },
  {
    "id": 52,
    "name": "#052",
    "description": "Yellow tall grass growing at high elevation. It sways back and forth in the sea breeze"
  },
  {
    "id": 53,
    "name": "#053",
    "description": "Yellow tall grass by the water. A nice resting spot for Pokémon after they're done swimmign"
  },
  {
    "id": 54,
    "name": "#054",
    "description": "Tall grass growing in a marsh. Pokémon use this to wipe mud off themselves"
  },
  {
    "id": 55,
    "name": "#055",
    "description": "A lone vending machine amid yellow tall grass. Gotta stay hydrated-even out in nature"
  },
  {
    "id": 56,
    "name": "#056",
    "description": "A bed of refreshing seashore flowers. Pokémon are drawn in by its gentle scent"
  },
  {
    "id": 57,
    "name": "#057",
    "description": "Seashore flowers rest beneath the leaves of a palm tree. Their tropical aroma drifts around the area"
  },
  {
    "id": 58,
    "name": "#058",
    "description": "A breeze whooshes over this cool flower bed. As the windmill turns, a floral aroma spreads far and wide."
  },
  {
    "id": 59,
    "name": "#059",
    "description": "The leaves of a palm tree serve as a parasol to Pokémon resting in the beach chair."
  },
  {
    "id": 60,
    "name": "#060",
    "description": "Kick back by a palm tree and feel the ocean breeze for the full tropical experience"
  },
  {
    "id": 61,
    "name": "#061",
    "description": "Empty cardboard boxes and a fluffy straw bed. Opinions are divided on which provides better sleep."
  },
  {
    "id": 62,
    "name": "#062",
    "description": "Scattered toys and cardboard. Just when you think you're done tidying up, the mess somehow returns."
  },
  {
    "id": 63,
    "name": "#063",
    "description": "A place to dump everyone's garbage. You might even spot some trash-hunting Pokémon here!"
  },
  {
    "id": 64,
    "name": "#064",
    "description": "Trash cans put in place to prevent littering. You can sometimes find Pokémon inside them"
  },
  {
    "id": 65,
    "name": "#065",
    "description": "Some trash left by a power pole. Its surroundings smell a little stinky"
  },
  {
    "id": 66,
    "name": "#066",
    "description": "After eating a snack, put your trash in the trash can. â¦Think Pokémon can remember to do that?"
  },
  {
    "id": 67,
    "name": "#067",
    "description": "Dishes on a table. There's even a menu, so it's just like being in a restaurant."
  },
  {
    "id": 68,
    "name": "#068",
    "description": "Wheel out the dishes nice and slow, because once they reach the table, it's chow time"
  },
  {
    "id": 69,
    "name": "#069",
    "description": "Bird Pokémon are sure to come and enjoy feasting on the plated food."
  },
  {
    "id": 70,
    "name": "#070",
    "description": "Enjoy teatime while admiring the potted tree. Pokémon can feel refreshed here"
  },
  {
    "id": 71,
    "name": "#071",
    "description": "Lounge under this parasol, and bask in the tropical vibes. Pokémon might enjoy relaxing here."
  },
  {
    "id": 72,
    "name": "#072",
    "description": "A stage bathed in dazzling light. It seems likely to attract attention-seeking Pokémon"
  },
  {
    "id": 73,
    "name": "#073",
    "description": "A pop-art box surrounded by balloons. What's in the box? Open it and find out!"
  },
  {
    "id": 74,
    "name": "#074",
    "description": "The colorful neon lights of this festival entrance glow brilliantly, especially at night"
  },
  {
    "id": 75,
    "name": "#075",
    "description": "Give your look a once-over in the mirror after you change clothes. A place to become your ideal self!"
  },
  {
    "id": 76,
    "name": "#076",
    "description": "The partition helps keep prying eyes away before you're ready for the public"
  },
  {
    "id": 77,
    "name": "#077",
    "description": "Pokémon will be fascinated by the fluffy yarn and the adorable crafts that can be made from it"
  },
  {
    "id": 78,
    "name": "#078",
    "description": "You can't jump in the hot spring without rinsing off at a shower first! Pokémon might enjoy soaking here"
  },
  {
    "id": 79,
    "name": "#079",
    "description": "Sitting by a campfire underneat a palm treeâ¦Let's kick back and cook some food"
  },
  {
    "id": 80,
    "name": "#080",
    "description": "Let's pack some cardboard boxes full of stuff and stack them on top of a cart!"
  },
  {
    "id": 81,
    "name": "#081",
    "description": "Nothing like a good nap when you're feeling sick. A caring Pokémon might even come to check in!"
  },
  {
    "id": 82,
    "name": "#082",
    "description": "Setting the bedside alarm clock makes waking up in the morning a breeze"
  },
  {
    "id": 83,
    "name": "#083",
    "description": "A long bench beside a vending machine. Pokémon might swing by to take a breather."
  },
  {
    "id": 84,
    "name": "#084",
    "description": "A trash can beside a vending machine. Doesn't look like there are any empty cans inside"
  },
  {
    "id": 85,
    "name": "#085",
    "description": "When you're done playing arcade games, you can hit up the punching game to get your body moving!"
  },
  {
    "id": 86,
    "name": "#086",
    "description": "This amazing facility generaes electriciy through the power of a waterfall"
  },
  {
    "id": 87,
    "name": "#087",
    "description": "When you fuel this amazing contraption, it generates electricity with the power of fire"
  },
  {
    "id": 88,
    "name": "#088",
    "description": "A cozy little dock on the beach. Swimming Pokémon might stop by now and then."
  },
  {
    "id": 89,
    "name": "#089",
    "description": "Light thre candle to read by firelight! This place feels spooky when night falls"
  },
  {
    "id": 90,
    "name": "#090",
    "description": "Stand in front of the wheel or ight by the cannons, and you'll feel like you're sailing the open seas!"
  },
  {
    "id": 91,
    "name": "#091",
    "description": "Put a register on a table, power it on, and boom! You'll be ready for business in no time"
  },
  {
    "id": 92,
    "name": "#092",
    "description": "Take a seat in front of the canvas and let your imagination run wild. Inspiration is waiting to strike!"
  },
  {
    "id": 93,
    "name": "#093",
    "description": "Putting an offering of food on this platter would surely delight Pokémon who live to eat"
  },
  {
    "id": 94,
    "name": "#094",
    "description": "The sofa and doll are both Pikachu! Some Pokémon might mistake them for the real Pikachu and stop by"
  },
  {
    "id": 95,
    "name": "#095",
    "description": "Being surrounded by all this cute furniture will make you feel perfectly pampered"
  },
  {
    "id": 96,
    "name": "#096",
    "description": "Relax on the sofa or lie down on the hammock, and you'll feel like you're in the lap of luxury."
  },
  {
    "id": 97,
    "name": "#097",
    "description": "A simple yet calming space. Pokémon are sure to be comfortable here."
  },
  {
    "id": 98,
    "name": "#098",
    "description": "A small plot made up of four tufts of red tall grass. Spots like this are often found in valleys"
  },
  {
    "id": 99,
    "name": "#099",
    "description": "Pokmon are drawn to this place, invited by the damp aroma of the red tall grass."
  },
  {
    "id": 100,
    "name": "#100",
    "description": "Lean against the rock in the tall grass, and take a break while admiring the large pointy tree."
  },
  {
    "id": 101,
    "name": "#101",
    "description": "While red tall grass often grows in valleys, it also thrives just fine on the waterside"
  },
  {
    "id": 102,
    "name": "#102",
    "description": "Red tall grass flourishes even in high-altitude areas like mountaintops"
  },
  {
    "id": 103,
    "name": "#103",
    "description": "The bags of dirt can be used as dumbbells. Perfect for Pokémon who love to train"
  },
  {
    "id": 104,
    "name": "#104",
    "description": "Numerous mountain flowers bloom to form an elegant and beautiful flower bed."
  },
  {
    "id": 105,
    "name": "#105",
    "description": "The elegant aroma of these mountain flowers wafts all throughout the area"
  },
  {
    "id": 106,
    "name": "#106",
    "description": "These elegant mountain flowers bloom beautifully, even right beside thew ater."
  },
  {
    "id": 107,
    "name": "#107",
    "description": "A stage set up in a field of flowers. Hop on the stump to bathe in the spotlight and feel just like a star"
  },
  {
    "id": 108,
    "name": "#108",
    "description": "A thriving vegetable field. Replacing the soil every so often provides fresh nutrients"
  },
  {
    "id": 109,
    "name": "#109",
    "description": "You can walk on top of the duckweed or jump into the water and float next to them"
  },
  {
    "id": 110,
    "name": "#110",
    "description": "All that nice, damp moss makes this a great location for Pokémon who love humid places"
  },
  {
    "id": 111,
    "name": "#111",
    "description": "A quiet, peaceful atmosphere. It looks like Pokémon could really unwind here"
  },
  {
    "id": 112,
    "name": "#112",
    "description": "A hot spring surrounded by green moss. Soak up the calming atmosphere as you soak in warm water."
  },
  {
    "id": 113,
    "name": "#113",
    "description": "Pokémon can also soak in a nice hot spring while enjoying beautiful scenery"
  },
  {
    "id": 114,
    "name": "#114",
    "description": "Some Pokémon enjoy moving between the hot spring and the cold bath to feel light and refreshed"
  },
  {
    "id": 115,
    "name": "#115",
    "description": "Nothin' but piping-hot lava here! Fire-type Pokémon simply can't resist visiting"
  },
  {
    "id": 116,
    "name": "#116",
    "description": "A big furnace with equipment next to it. Someone might come to light the flame"
  },
  {
    "id": 117,
    "name": "#117",
    "description": "It looks like construction is underway. Some strong Pokémon might show up to help"
  },
  {
    "id": 118,
    "name": "#118",
    "description": "The thick moss near the stalagmites and the long glowing lantern create a slightly creepy vibe."
  },
  {
    "id": 119,
    "name": "#119",
    "description": "Looks like someone snuck a snack by some storage containers. Pokémon might like a spot like this"
  },
  {
    "id": 120,
    "name": "#120",
    "description": "There's no better thrill than lifting the lid off a dish to reveal today's meal"
  },
  {
    "id": 121,
    "name": "#121",
    "description": "Prepare some side dishes while you wait for bread to finish baking."
  },
  {
    "id": 122,
    "name": "#122",
    "description": "Wash your dishes and ingredients, then cook away on the stove. What's on the menu for today?"
  },
  {
    "id": 123,
    "name": "#123",
    "description": "Help yourself to food and drinks, and have a total blast with all your friends"
  },
  {
    "id": 124,
    "name": "#124",
    "description": "Kick back with a drink in your hand and use the tablet to reminisce over some photos"
  },
  {
    "id": 125,
    "name": "#125",
    "description": "Bird Pokémon may swoop in and use the microphone to show off their singing skills"
  },
  {
    "id": 126,
    "name": "#126",
    "description": "This stage was made for just one thing-now get up there and SING!"
  },
  {
    "id": 127,
    "name": "#127",
    "description": "Pokémon can feel the rhythm here and get pumped for a training session"
  },
  {
    "id": 128,
    "name": "#128",
    "description": "Reading feels even more relaxing when you throw on some background music"
  },
  {
    "id": 129,
    "name": "#129",
    "description": "Anything can look like a masterpiece if you pop it on an exhibition stand!"
  },
  {
    "id": 130,
    "name": "#130",
    "description": "Even a simple locker room can have a refreshing atmosphere with the addition of a houseplant or two."
  },
  {
    "id": 131,
    "name": "#131",
    "description": "A photoworthy bronze statue of three Pokémon. Their combined cuteness is sure to attract a crowd!"
  },
  {
    "id": 132,
    "name": "#132",
    "description": "Absolutely no crossing while the bar is lowered! Butâ¦will Pokémon actually sotp and wait?"
  },
  {
    "id": 133,
    "name": "#133",
    "description": "With a stove, a sink, and some key cooking equipment, this place is a chef's dream"
  },
  {
    "id": 134,
    "name": "#134",
    "description": "Every single piece of this furniture set is top-noth, creating the ultimate air of luxury"
  },
  {
    "id": 135,
    "name": "#135",
    "description": "A monochromatic space with weighty furniture. Light the lantern to add another layer of calm"
  },
  {
    "id": 136,
    "name": "#136",
    "description": "Stylishly simple. The modern design gives off a sense of classiness"
  },
  {
    "id": 137,
    "name": "#137",
    "description": "A small plot made up of four tufts of pink tall grass. Spots like this are often found in the skylands"
  },
  {
    "id": 138,
    "name": "#138",
    "description": "Growing in the shade of a tree, this pink grass is just the tiniest bit damp"
  },
  {
    "id": 139,
    "name": "#139",
    "description": "The pink of the tall grass contrasts beautifully with the blue hues of the water."
  },
  {
    "id": 140,
    "name": "#140",
    "description": "Tall pink grass from way above the clouds. Even strong winds can't stop it from growing"
  },
  {
    "id": 141,
    "name": "#141",
    "description": "A concrete pipe that hasn't been used in al ong time. The hollow interior is perfect for a secret base."
  },
  {
    "id": 142,
    "name": "#142",
    "description": "A cute field full of lots of puffy skyland flowers"
  },
  {
    "id": 143,
    "name": "#143",
    "description": "Poofy skyland flowers bloom cutely-even in the cool shade of a tree"
  },
  {
    "id": 144,
    "name": "#144",
    "description": "Water can't diminish the gentle aroma wafting from these skyland flowers."
  },
  {
    "id": 145,
    "name": "#145",
    "description": "Board the canoe, or just enjoy some tranquil time relaxing by the waterside"
  },
  {
    "id": 146,
    "name": "#146",
    "description": "Use the torches to light a path to the waterfall. Pokémon might stop by to check it out"
  },
  {
    "id": 147,
    "name": "#147",
    "description": "A comfy birdhouse with a neatly trimmed hedge. You can almost hear chirping"
  },
  {
    "id": 148,
    "name": "#148",
    "description": "An ordinary bathroom. Pokémon might stop by to wash themselves."
  },
  {
    "id": 149,
    "name": "#149",
    "description": "Stop your bicycle here for a quick break. Pokémon sometimes hide behind the vending machine."
  },
  {
    "id": 150,
    "name": "#150",
    "description": "If you're feeling chilly, you can sit by this fireplace and it will gently warm you."
  },
  {
    "id": 151,
    "name": "#151",
    "description": "Sit in front of the crystal ball and focus to gain mastery over your psychic powersâ¦maybe."
  },
  {
    "id": 152,
    "name": "#152",
    "description": "Maybe using psychic power to peer into the crystal ball will give you a glimpse of the futureâ¦"
  },
  {
    "id": 153,
    "name": "#153",
    "description": "A lone TV left out with the garbage. It looks like it can still be turned on."
  },
  {
    "id": 154,
    "name": "#154",
    "description": "A dumping ground where you can even throw away large items. Unwanted appliances can go here!"
  },
  {
    "id": 155,
    "name": "#155",
    "description": "You and Arcanine, interrogating perps side by sideâ¦ The tension in the air is palpable"
  },
  {
    "id": 156,
    "name": "#156",
    "description": "Looks like repairs are being carried out here. Only workers are allowed in-no exceptions!"
  },
  {
    "id": 157,
    "name": "#157",
    "description": "Washing your face and drying it off with a towel feels refreshing. Check out how you look in the mirror!"
  },
  {
    "id": 158,
    "name": "#158",
    "description": "Some big speakers and a TV make this space feel just likea movie theater"
  },
  {
    "id": 159,
    "name": "#159",
    "description": "Just sitting at this desk with a pencil in hand is enough to make you feel a little smarter"
  },
  {
    "id": 160,
    "name": "#160",
    "description": "A large TV with a rhythm game hooked up to it. Step on the mats in time with the beat!"
  },
  {
    "id": 161,
    "name": "#161",
    "description": "Put lots of cleaner on the Mareep spone and make that bathroom shine"
  },
  {
    "id": 162,
    "name": "#162",
    "description": "Making sure your skin is moisturized will ensure your makeup comes out even more perfectly than usual!"
  },
  {
    "id": 163,
    "name": "#163",
    "description": "Light the lamp to peruse the books at your leisure, even in the dark ofnight"
  },
  {
    "id": 164,
    "name": "#164",
    "description": "Players site side by side here to game against each other!P okémon might come here to play."
  },
  {
    "id": 165,
    "name": "#165",
    "description": "To play on the big slide or with the toysâ¦ Now that's a hard choice"
  },
  {
    "id": 166,
    "name": "#166",
    "description": "Sit on the office chair and type away at the computer. If you feel tired, grab a beverage and take a break!"
  },
  {
    "id": 167,
    "name": "#167",
    "description": "Packed with old documents and unused equipment. Lost Pokémon sometimes wander inside."
  },
  {
    "id": 168,
    "name": "#168",
    "description": "A space for conducting experiments. Someone may have left their research notes behind."
  },
  {
    "id": 169,
    "name": "#169",
    "description": "Keep up with your research, and someday you might become as wide and learned as Professor Tangrowth!"
  },
  {
    "id": 170,
    "name": "#170",
    "description": "Today's research topic is Pokémon's role in science! Some data has been entered into the computer"
  },
  {
    "id": 171,
    "name": "#171",
    "description": "Anyone can freely pick up and enjoy the newspapers and magazines found here"
  },
  {
    "id": 172,
    "name": "#172",
    "description": "The rhythm of the big drum, the spotlights on the boo-in-the-boxâ¦ The suspense is palpable!"
  },
  {
    "id": 173,
    "name": "#173",
    "description": "A conspicuous button next to a boo-in-the-box. To press, or not to press, that is the questino."
  },
  {
    "id": 174,
    "name": "#174",
    "description": "Say cheese! Stick your face in the cutoutboard and snap a photo to commemorate your hoke."
  },
  {
    "id": 175,
    "name": "#175",
    "description": "For some reason, the tires are more enticing than the big slideâ¦ Yeah! Let's play with all the different tires!"
  },
  {
    "id": 176,
    "name": "#176",
    "description": "Just power up the cash register, and you'll be able to trade with your friends-even out in nature!"
  },
  {
    "id": 177,
    "name": "#177",
    "description": "Construction needs a lot of electricity! You can use any leftover lumber as fuel"
  },
  {
    "id": 178,
    "name": "#178",
    "description": "Once you emply the spirit of the warrior, you will be able to move even the heaviest of boulders"
  },
  {
    "id": 179,
    "name": "#179",
    "description": "A comfy couch in front of an organization's emblem. Sitting here makes you feel like a boss."
  },
  {
    "id": 180,
    "name": "#180",
    "description": "The gentle sway of these nine blazing flames gives their surroundings a subtly mystical ambeience"
  },
  {
    "id": 181,
    "name": "#181",
    "description": "Some Pokémon might mistake all these dolls for the real things"
  },
  {
    "id": 182,
    "name": "#182",
    "description": "A space perfectly tailored for gaming. Take a seat and immerse yourself in the world of games!"
  },
  {
    "id": 183,
    "name": "#183",
    "description": "The colorful pop-art furniture gives off a cheerful atmosphere that'll lift your spirits in no time!"
  },
  {
    "id": 184,
    "name": "#184",
    "description": "Cast a line and wait patiently. Perhaps a Water-type Pokémon will appear!"
  },
  {
    "id": 185,
    "name": "#185",
    "description": "Ocean fishing can be fun! You may meet different species of Pokémon than you would in fresh water."
  },
  {
    "id": 186,
    "name": "#186",
    "description": "Pokémon live in marshlands too! Try casting your lin into some swampy water sometime"
  },
  {
    "id": 187,
    "name": "#187",
    "description": "Pokémon enjoying a nice dip in the hot spring might be lure in with some bait."
  },
  {
    "id": 188,
    "name": "#188",
    "description": "Catch Pokémon by fishing in magma. Wait, how do you do that without the line melting?!"
  },
  {
    "id": 189,
    "name": "#189",
    "description": "The wail of the guitar marks the start of this amped-up performance"
  },
  {
    "id": 190,
    "name": "#190",
    "description": "The hum of the bass guitar marks the start of al ow-key musical performance"
  },
  {
    "id": 191,
    "name": "#191",
    "description": "A slightly eerie space where a mysterious ritual appears to be underway..."
  },
  {
    "id": 192,
    "name": "#192",
    "description": "A slightly mystical space where a mysterious ritual appears to be underway..."
  },
  {
    "id": 193,
    "name": "#193",
    "description": "A display of ancient Pokémon fossils. This fine skeletal specimen was once ruler of the skies"
  },
  {
    "id": 194,
    "name": "#194",
    "description": "A display of an ancient Pokémon fossil. This fossilized skull is as hard as iron"
  },
  {
    "id": 195,
    "name": "#195",
    "description": "A display of ancient Pokémon fossils. This speciment's skull was harder than steel"
  },
  {
    "id": 196,
    "name": "#196",
    "description": "A display of an ancient Pokémon fossil. It features a hard neck frill that looks like a shield."
  },
  {
    "id": 197,
    "name": "#197",
    "description": "A display of ancient Pokémon fossils. This speciment's large neck frill was as sturdy as a fortress wall."
  },
  {
    "id": 198,
    "name": "#198",
    "description": "A display of an ancient Pokémon fossil. It features a piece of a jawbone that could crush anything,"
  },
  {
    "id": 199,
    "name": "#199",
    "description": "A display of ancient Pokémon fossils. This fine skeletal specimen was once the ruler of the land."
  },
  {
    "id": 200,
    "name": "#200",
    "description": "A display of an ancient Pokémon fossil. This piece of neck sail was once frozen in ice."
  },
  {
    "id": 201,
    "name": "#201",
    "description": "A display of ancient Pokémon fossils. The specimen's beautiful neck sail resembles an aurora."
  },
  {
    "id": 202,
    "name": "#202",
    "description": "A clear-blue ice-cream float. It's like looking deep into the ocean"
  },
  {
    "id": 203,
    "name": "#203",
    "description": "A basket of crispy potato stars. They're shockingly delicious!"
  },
  {
    "id": 204,
    "name": "#204",
    "description": "Putting hot sauce on this round pizza will make it so spicy that you'll feel like you're breathing fire."
  },
  {
    "id": 205,
    "name": "#205",
    "description": "Teatime is always midday. Take a seat, have a snack, and bask in the elegance of it all."
  },
  {
    "id": 206,
    "name": "#206",
    "description": "Cookies made from dark chocolate. They have a subtle, comforting taste without being overly sweet"
  },
  {
    "id": 207,
    "name": "#207",
    "description": "A sandwich packed with greens and veggies would really hit the spot right now"
  },
  {
    "id": 208,
    "name": "#208",
    "description": "Shaved ice served with frozen toppings. Eating this could make you feel teeth-chatteringly chilly"
  },
  {
    "id": 209,
    "name": "#209",
    "description": "The large ribbon and heart decorations make this cake look quite lovely. It tastes incredibly sweet."
  }
]
