# Legendary/Mythical Pokémon details from Serebii
# Auto-generated by scrape.py — do not edit manually

LEGENDARIES = [
  {
    "name": "As with many Pokémon games, Legendary Pokémon can be found throughout the game. In Pokémon Pokopia, they act much like other Pokémon with their own specialties, desires and so forth but there are a few changes Legendary and Mythical Pokémon have a greater effect on the Environment level of the area you bring them to. As you improve their comfort level, it becomes easier to raise the entire environment level of the area",
    "details": "",
    "source": "legendary",
    "national_id": null
  },
  {
    "name": "Several of the Legendary Pokémon can be obtained by going through various Dream Islands. If you go to some Dream Islands, you will have a chance of getting the Legendary Beasts and Mewtwo. You can fine tune the islands you get using certain dolls to start your journey but it isn't a guarantee. Eevee Doll: Suicune Pikachu Doll: Raikou Arcanine Doll: Entei Dragonite Doll: Mewtwo Once you have spoken to the Pokémon, you will be able to bring them back to the region and set them up in a home.",
    "details": "",
    "source": "legendary",
    "national_id": null
  },
  {
    "name": "In Palette Town, you will be able to find three special kits around the area. If you go to build these kits, they will require 15 Pokémon as well as a substantial amont of resources. When built, you will find the Legenday Bird Pokémon within > KitLegendary PokémonRequirements Freezing ChambersArticuno50 Stone50 Ice10 Crystal Fragments10 PokéMetal Abandoned Power PlantZapdos50 Copper Ingot50 Gold Ingot50 Sea Glass Fragments50 Brick10 PokéMetal Altar of the FlameMoltres50 Copper Ingot50 Gold Ignot50 Lava Block10 PokéMetal",
    "details": "Kit Legendary Pokémon Requirements Freezing Chambers Articuno 50 Stone50 Ice10 Crystal Fragments10 PokéMetal Abandoned Power Plant Zapdos 50 Copper Ingot50 Gold Ingot50 Sea Glass Fragments50 Brick10 PokéMetal Altar of the Flame Moltres 50 Copper Ingot50 Gold Ignot50 Lava Block10 PokéMetal ",
    "source": "legendary",
    "national_id": null
  },
  {
    "name": "Kit",
    "details": "Legendary Pokémon Requirements",
    "source": "legendary",
    "national_id": null
  },
  {
    "name": "Freezing Chambers",
    "details": "Articuno 50 Stone50 Ice10 Crystal Fragments10 PokéMetal",
    "source": "legendary",
    "national_id": null
  },
  {
    "name": "Abandoned Power Plant",
    "details": "Zapdos 50 Copper Ingot50 Gold Ingot50 Sea Glass Fragments50 Brick10 PokéMetal",
    "source": "legendary",
    "national_id": null
  },
  {
    "name": "Altar of the Flame",
    "details": "Moltres 50 Copper Ingot50 Gold Ignot50 Lava Block10 PokéMetal",
    "source": "legendary",
    "national_id": null
  },
  {
    "name": "Throughout your gameplay, you will be seeing Ho-Oh and Lugia flying overhead. If you wait for them to leave, they will drop off a Rainbow Feather or Silver Feather respectively.After you have befriended Articuno, Zapdos and Moltres, you will get a recipe for a Tidal Bell which requires 5 Rare PokéMetal and 5 Silver Feather to make, and if you befriend Raikou, Entei & Suicune you'll get the recipe for the Clear Bell which requires 5 Rare PokéMetal and 5 Rainbow Feather to make. With these items in hand, when Ho-Oh or Lugia fly overhead, you can place tohose items and ring the bell to get them to come down to talk and befriend.",
    "details": "",
    "source": "legendary",
    "national_id": null
  },
  {
    "name": "After you have finished Rocky Ridges, you will be able to befriend Volcanion. To get it to reappear so it can move in, you will need to set up a second party in Rocky Ridges which involves getting the mood up to 100 again. Then, when the party is finished, load up a cannon and some fireworks and Volcanion will appear again and ask to join as the parties always seem fun. From here, it will now live in Rocky Ridges.",
    "details": "",
    "source": "legendary",
    "national_id": null
  },
  {
    "name": "Mew is a bit different in how it is found. Unlike the random ones found in the Dream Island from the get-go, or the ones that you find in the story before finding them in Dream Island, here you need to find 27 different Mysterious Slates. These can be found randomly in shiny patches of ground. Then, take then to the ruins near the Pokémon Center in the Withered Wastelands. Put the blocks on the corresponding tile to make a Mew picture and Mew will then be available to find.",
    "details": "",
    "source": "legendary",
    "national_id": null
  }
]
