# All Pokémon in Pokémon Pokopia from Serebii
# Auto-generated by scrape.py — do not edit manually

POKEMON = [
  {
    "pokopia_num": 1,
    "name": "Bulbasaur",
    "national_id": 1,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 2,
    "name": "Ivysaur",
    "national_id": 2,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 3,
    "name": "Venusaur",
    "national_id": 3,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 4,
    "name": "Charmander",
    "national_id": 4,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 5,
    "name": "Charmeleon",
    "national_id": 5,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 6,
    "name": "Charizard",
    "national_id": 6,
    "specialties": [
      "BurnFly",
      "Burn",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 7,
    "name": "Squirtle",
    "national_id": 7,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 8,
    "name": "Wartortle",
    "national_id": 8,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 9,
    "name": "Blastoise",
    "national_id": 9,
    "specialties": [
      "WaterTrade",
      "Water",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 10,
    "name": "Pidgey",
    "national_id": 16,
    "specialties": [
      "FlySearch",
      "Fly",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 11,
    "name": "Pidgeotto",
    "national_id": 17,
    "specialties": [
      "FlySearch",
      "Fly",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 12,
    "name": "Pidgeot",
    "national_id": 18,
    "specialties": [
      "FlyChop",
      "Fly",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 13,
    "name": "Oddish",
    "national_id": 43,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 14,
    "name": "Gloom",
    "national_id": 44,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 15,
    "name": "Vileplume",
    "national_id": 45,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 16,
    "name": "Bellossom",
    "national_id": 182,
    "specialties": [
      "GrowHype",
      "Grow",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 17,
    "name": "Paras",
    "national_id": 46,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 18,
    "name": "Parasect",
    "national_id": 47,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 19,
    "name": "Venonat",
    "national_id": 48,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 20,
    "name": "Venomoth",
    "national_id": 49,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 21,
    "name": "Bellsprout",
    "national_id": 69,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 22,
    "name": "Weepinbell",
    "national_id": 70,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 23,
    "name": "Victreebel",
    "national_id": 71,
    "specialties": [
      "GrowChop",
      "Grow",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 24,
    "name": "Slowpoke",
    "national_id": 79,
    "specialties": [
      "WaterYawn",
      "Water",
      "Yawn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 25,
    "name": "Slowbro",
    "national_id": 80,
    "specialties": [
      "WaterTrade",
      "Water",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 26,
    "name": "Slowking",
    "national_id": 199,
    "specialties": [
      "WaterTeleport",
      "Water",
      "Teleport"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 27,
    "name": "Magnemite",
    "national_id": 81,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 28,
    "name": "Magneton",
    "national_id": 82,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 29,
    "name": "Magnezone",
    "national_id": 462,
    "specialties": [
      "GenerateRecycle",
      "Generate",
      "Recycle"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 30,
    "name": "Onix",
    "national_id": 95,
    "specialties": [
      "CrushBulldoze",
      "Crush",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 31,
    "name": "Steelix",
    "national_id": 208,
    "specialties": [
      "CrushBulldoze",
      "Crush",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 32,
    "name": "Cubone",
    "national_id": 104,
    "specialties": [
      "Build",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 33,
    "name": "Marowak",
    "national_id": 105,
    "specialties": [
      "Build",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 34,
    "name": "Tyrogue",
    "national_id": 236,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 35,
    "name": "Hitmonlee",
    "national_id": 106,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 36,
    "name": "Hitmonchan",
    "national_id": 107,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 37,
    "name": "Hitmontop",
    "national_id": 237,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 38,
    "name": "Koffing",
    "national_id": 109,
    "specialties": [
      "Recycle",
      "Recycle"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 39,
    "name": "Weezing",
    "national_id": 110,
    "specialties": [
      "Recycle",
      "Recycle"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 40,
    "name": "Tangela",
    "national_id": 114,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 41,
    "name": "Professor Tangrowth",
    "national_id": null,
    "specialties": [
      "Appraise",
      "Appraise"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 41,
    "name": "Tangrowth",
    "national_id": 465,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 42,
    "name": "Scyther",
    "national_id": 123,
    "specialties": [
      "Chop",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 43,
    "name": "Scizor",
    "national_id": 212,
    "specialties": [
      "Chop",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 44,
    "name": "Pinsir",
    "national_id": 127,
    "specialties": [
      "ChopBuild",
      "Chop",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 45,
    "name": "Magikarp",
    "national_id": 129,
    "specialties": [
      "???",
      "???"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 46,
    "name": "Gyarados",
    "national_id": 130,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 47,
    "name": "Ditto",
    "national_id": 132,
    "specialties": [
      "Transform",
      "Transform"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 48,
    "name": "Hoothoot",
    "national_id": 163,
    "specialties": [
      "TradeFly",
      "Trade",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 49,
    "name": "Noctowl",
    "national_id": 164,
    "specialties": [
      "TradeFly",
      "Trade",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 50,
    "name": "Heracross",
    "national_id": 214,
    "specialties": [
      "ChopBuild",
      "Chop",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 51,
    "name": "Volbeat",
    "national_id": 313,
    "specialties": [
      "Hype",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 52,
    "name": "Illumise",
    "national_id": 314,
    "specialties": [
      "Hype",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 53,
    "name": "Gulpin",
    "national_id": 316,
    "specialties": [
      "Storage",
      "Storage"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 54,
    "name": "Swalot",
    "national_id": 317,
    "specialties": [
      "Storage",
      "Storage"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 55,
    "name": "Cacnea",
    "national_id": 331,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 56,
    "name": "Cacturne",
    "national_id": 332,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 57,
    "name": "Combee",
    "national_id": 415,
    "specialties": [
      "Litter",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 58,
    "name": "Vespiquen",
    "national_id": 416,
    "specialties": [
      "Gather HoneySearch",
      "Gather Honey",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 59,
    "name": "Shellos",
    "national_id": 422,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 59,
    "name": "Shellos East Sea",
    "national_id": null,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 60,
    "name": "Gastrodon",
    "national_id": 423,
    "specialties": [
      "WaterTrade",
      "Water",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 60,
    "name": "Gastrodon East Sea",
    "national_id": null,
    "specialties": [
      "WaterTrade",
      "Water",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 61,
    "name": "Drifloon",
    "national_id": 425,
    "specialties": [
      "Dream Island",
      "Dream Island"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 62,
    "name": "Drifblim",
    "national_id": 426,
    "specialties": [
      "FlyGather",
      "Fly",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 63,
    "name": "Drilbur",
    "national_id": 529,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 64,
    "name": "Excadrill",
    "national_id": 530,
    "specialties": [
      "SearchChop",
      "Search",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 65,
    "name": "Timburr",
    "national_id": 532,
    "specialties": [
      "Build",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 66,
    "name": "Gurdurr",
    "national_id": 533,
    "specialties": [
      "Build",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 67,
    "name": "Conkeldurr",
    "national_id": 534,
    "specialties": [
      "BuildCrush",
      "Build",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 68,
    "name": "Litwick",
    "national_id": 607,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 69,
    "name": "Lampent",
    "national_id": 608,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 70,
    "name": "Chandelure",
    "national_id": 609,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 71,
    "name": "Axew",
    "national_id": 610,
    "specialties": [
      "Chop",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 72,
    "name": "Fraxure",
    "national_id": 611,
    "specialties": [
      "Chop",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 73,
    "name": "Haxorus",
    "national_id": 612,
    "specialties": [
      "ChopLitter",
      "Chop",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 74,
    "name": "Goomy",
    "national_id": 704,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 75,
    "name": "Sliggoo",
    "national_id": 705,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 76,
    "name": "Goodra",
    "national_id": 706,
    "specialties": [
      "WaterTrade",
      "Water",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 77,
    "name": "Cramorant",
    "national_id": 845,
    "specialties": [
      "FlyWater",
      "Fly",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 78,
    "name": "Pichu",
    "national_id": 172,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 79,
    "name": "Peakychu",
    "national_id": null,
    "specialties": [
      "Illuminate",
      "Illuminate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 79,
    "name": "Pikachu",
    "national_id": 25,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 80,
    "name": "Raichu",
    "national_id": 26,
    "specialties": [
      "GenerateHype",
      "Generate",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 81,
    "name": "Zubat",
    "national_id": 41,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 82,
    "name": "Golbat",
    "national_id": 42,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 83,
    "name": "Crobat",
    "national_id": 169,
    "specialties": [
      "SearchChop",
      "Search",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 84,
    "name": "Meowth",
    "national_id": 52,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 85,
    "name": "Persian",
    "national_id": 53,
    "specialties": [
      "TradeSearch",
      "Trade",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 86,
    "name": "Psyduck",
    "national_id": 54,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 87,
    "name": "Golduck",
    "national_id": 55,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 88,
    "name": "Growlithe",
    "national_id": 58,
    "specialties": [
      "BurnSearch",
      "Burn",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 89,
    "name": "Arcanine",
    "national_id": 59,
    "specialties": [
      "BurnSearch",
      "Burn",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 90,
    "name": "Farfetch'd",
    "national_id": 83,
    "specialties": [
      "ChopBuild",
      "Chop",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 91,
    "name": "Grimer",
    "national_id": 88,
    "specialties": [
      "Litter",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 92,
    "name": "Muk",
    "national_id": 89,
    "specialties": [
      "Litter",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 93,
    "name": "Gastly",
    "national_id": 92,
    "specialties": [
      "GatherTrade",
      "Gather",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 94,
    "name": "Haunter",
    "national_id": 93,
    "specialties": [
      "GatherTrade",
      "Gather",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 95,
    "name": "Gengar",
    "national_id": 94,
    "specialties": [
      "GatherTrade",
      "Gather",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 96,
    "name": "Voltorb",
    "national_id": 100,
    "specialties": [
      "GenerateExplode",
      "Generate",
      "Explode"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 97,
    "name": "Electrode",
    "national_id": 101,
    "specialties": [
      "GenerateExplode",
      "Generate",
      "Explode"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 98,
    "name": "Exeggcute",
    "national_id": 102,
    "specialties": [
      "GrowTeleport",
      "Grow",
      "Teleport"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 99,
    "name": "Exeggutor",
    "national_id": 103,
    "specialties": [
      "GrowTeleport",
      "Grow",
      "Teleport"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 100,
    "name": "Happiny",
    "national_id": 440,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 101,
    "name": "Chansey",
    "national_id": 113,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 102,
    "name": "Blissey",
    "national_id": 242,
    "specialties": [
      "TradeLitter",
      "Trade",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 103,
    "name": "Elekid",
    "national_id": 239,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 104,
    "name": "Electabuzz",
    "national_id": 125,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 105,
    "name": "Electivire",
    "national_id": 466,
    "specialties": [
      "GenerateCrush",
      "Generate",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 106,
    "name": "Lapras",
    "national_id": 131,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 107,
    "name": "Munchlax",
    "national_id": 446,
    "specialties": [
      "Bulldoze",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 108,
    "name": "Mosslax",
    "national_id": null,
    "specialties": [
      "Eat",
      "Eat"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 108,
    "name": "Snorlax",
    "national_id": 143,
    "specialties": [
      "TradeBulldoze",
      "Trade",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 109,
    "name": "Spinarak",
    "national_id": 167,
    "specialties": [
      "Litter",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 110,
    "name": "Ariados",
    "national_id": 168,
    "specialties": [
      "Litter",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 111,
    "name": "Mareep",
    "national_id": 179,
    "specialties": [
      "GenerateLitter",
      "Generate",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 112,
    "name": "Flaaffy",
    "national_id": 180,
    "specialties": [
      "GenerateLitter",
      "Generate",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 113,
    "name": "Ampharos",
    "national_id": 181,
    "specialties": [
      "GenerateTrade",
      "Generate",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 114,
    "name": "Azurill",
    "national_id": 298,
    "specialties": [
      "WaterHype",
      "Water",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 115,
    "name": "Marill",
    "national_id": 183,
    "specialties": [
      "WaterHype",
      "Water",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 116,
    "name": "Azumarill",
    "national_id": 184,
    "specialties": [
      "WaterBuild",
      "Water",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 117,
    "name": "Paldean Wooper",
    "national_id": null,
    "specialties": [
      "Litter",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 118,
    "name": "Clodsire",
    "national_id": 980,
    "specialties": [
      "LitterBulldoze",
      "Litter",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 119,
    "name": "Smeargle",
    "national_id": null,
    "specialties": [
      "Paint",
      "Paint"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 120,
    "name": "Torchic",
    "national_id": 255,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 121,
    "name": "Combusken",
    "national_id": 256,
    "specialties": [
      "BurnBuild",
      "Burn",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 122,
    "name": "Blaziken",
    "national_id": 257,
    "specialties": [
      "BurnBuild",
      "Burn",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 123,
    "name": "Wingull",
    "national_id": 278,
    "specialties": [
      "WaterFly",
      "Water",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 124,
    "name": "Pelipper",
    "national_id": 279,
    "specialties": [
      "WaterFly",
      "Water",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 125,
    "name": "Makuhita",
    "national_id": 296,
    "specialties": [
      "BuildBulldoze",
      "Build",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 126,
    "name": "Hariyama",
    "national_id": 297,
    "specialties": [
      "BuildBulldoze",
      "Build",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 127,
    "name": "Absol",
    "national_id": 359,
    "specialties": [
      "Chop",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 128,
    "name": "Piplup",
    "national_id": 393,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 129,
    "name": "Prinplup",
    "national_id": 394,
    "specialties": [
      "WaterTrade",
      "Water",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 130,
    "name": "Empoleon",
    "national_id": 395,
    "specialties": [
      "WaterTrade",
      "Water",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 131,
    "name": "Audino",
    "national_id": 531,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 132,
    "name": "Trubbish",
    "national_id": 568,
    "specialties": [
      "Recycle",
      "Recycle"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 133,
    "name": "Garbodor",
    "national_id": 569,
    "specialties": [
      "RecycleLitter",
      "Recycle",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 134,
    "name": "Zorua",
    "national_id": 570,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 135,
    "name": "Zoroark",
    "national_id": 571,
    "specialties": [
      "TradeChop",
      "Trade",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 136,
    "name": "Minccino",
    "national_id": 572,
    "specialties": [
      "Gather",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 137,
    "name": "Cinccino",
    "national_id": 573,
    "specialties": [
      "GatherRecycle",
      "Gather",
      "Recycle"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 138,
    "name": "Grubbin",
    "national_id": 736,
    "specialties": [
      "Chop",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 139,
    "name": "Charjabug",
    "national_id": 737,
    "specialties": [
      "GenerateChop",
      "Generate",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 140,
    "name": "Vikavolt",
    "national_id": 738,
    "specialties": [
      "GenerateChop",
      "Generate",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 141,
    "name": "Mimikyu",
    "national_id": 778,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 142,
    "name": "Pawmi",
    "national_id": 921,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 143,
    "name": "Pawmo",
    "national_id": 922,
    "specialties": [
      "GenerateCrush",
      "Generate",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 144,
    "name": "Pawmot",
    "national_id": 923,
    "specialties": [
      "GenerateCrush",
      "Generate",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 145,
    "name": "Tatsugiri Curly Form",
    "national_id": null,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 145,
    "name": "Tatsugiri Droopy Form",
    "national_id": null,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 145,
    "name": "Tatsugiri Stretchy Form",
    "national_id": null,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 146,
    "name": "Ekans",
    "national_id": 23,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 147,
    "name": "Arbok",
    "national_id": 24,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 148,
    "name": "Cleffa",
    "national_id": 173,
    "specialties": [
      "Hype",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 149,
    "name": "Clefairy",
    "national_id": 35,
    "specialties": [
      "Hype",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 150,
    "name": "Clefable",
    "national_id": 36,
    "specialties": [
      "HypeTrade",
      "Hype",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 151,
    "name": "Igglybuff",
    "national_id": 174,
    "specialties": [
      "Hype",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 152,
    "name": "Jigglypuff",
    "national_id": 39,
    "specialties": [
      "Hype",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 153,
    "name": "Wigglytuff",
    "national_id": 40,
    "specialties": [
      "HypeTrade",
      "Hype",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 154,
    "name": "Diglett",
    "national_id": 50,
    "specialties": [
      "Hype",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 155,
    "name": "Dugtrio",
    "national_id": 51,
    "specialties": [
      "HypeCrush",
      "Hype",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 156,
    "name": "Machop",
    "national_id": 66,
    "specialties": [
      "BuildGather",
      "Build",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 157,
    "name": "Machoke",
    "national_id": 67,
    "specialties": [
      "BuildGather",
      "Build",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 158,
    "name": "Machamp",
    "national_id": 68,
    "specialties": [
      "BuildGather",
      "Build",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 159,
    "name": "Geodude",
    "national_id": 74,
    "specialties": [
      "Crush",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 160,
    "name": "Graveler",
    "national_id": 75,
    "specialties": [
      "Crush",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 161,
    "name": "Golem",
    "national_id": 76,
    "specialties": [
      "CrushTrade",
      "Crush",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 162,
    "name": "Magby",
    "national_id": 240,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 163,
    "name": "Magmar",
    "national_id": 126,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 164,
    "name": "Magmortar",
    "national_id": 467,
    "specialties": [
      "BurnCrush",
      "Burn",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 165,
    "name": "Bonsly",
    "national_id": 438,
    "specialties": [
      "Bulldoze",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 166,
    "name": "Sudowoodo",
    "national_id": 185,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 167,
    "name": "Murkrow",
    "national_id": 198,
    "specialties": [
      "TradeFly",
      "Trade",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 168,
    "name": "Honchkrow",
    "national_id": 430,
    "specialties": [
      "TradeFly",
      "Trade",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 169,
    "name": "Larvitar",
    "national_id": 246,
    "specialties": [
      "CrushBulldoze",
      "Crush",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 170,
    "name": "Pupitar",
    "national_id": 247,
    "specialties": [
      "CrushBulldoze",
      "Crush",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 171,
    "name": "Tyranitar",
    "national_id": 248,
    "specialties": [
      "CrushBulldoze",
      "Crush",
      "Bulldoze"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 172,
    "name": "Lotad",
    "national_id": 270,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 173,
    "name": "Lombre",
    "national_id": 271,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 174,
    "name": "Ludicolo",
    "national_id": 272,
    "specialties": [
      "WaterHype",
      "Water",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 175,
    "name": "Mawile",
    "national_id": 303,
    "specialties": [
      "TradeBuild",
      "Trade",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 176,
    "name": "Torkoal",
    "national_id": 324,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 177,
    "name": "Kricketot",
    "national_id": 401,
    "specialties": [
      "Hype",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 178,
    "name": "Kricketune",
    "national_id": 402,
    "specialties": [
      "Hype",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 179,
    "name": "Chatot",
    "national_id": 441,
    "specialties": [
      "HypeFly",
      "Hype",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 180,
    "name": "Riolu",
    "national_id": 447,
    "specialties": [
      "Build",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 181,
    "name": "Lucario",
    "national_id": 448,
    "specialties": [
      "Build",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 182,
    "name": "Stereo Rotom",
    "national_id": null,
    "specialties": [
      "DJ",
      "DJ"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 183,
    "name": "Larvesta",
    "national_id": 636,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 184,
    "name": "Volcarona",
    "national_id": 637,
    "specialties": [
      "BurnLitter",
      "Burn",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 185,
    "name": "Rowlet",
    "national_id": 722,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 186,
    "name": "Dartrix",
    "national_id": 723,
    "specialties": [
      "GrowChop",
      "Grow",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 187,
    "name": "Decidueye",
    "national_id": 724,
    "specialties": [
      "GrowChop",
      "Grow",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 188,
    "name": "Scorbunny",
    "national_id": 813,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 189,
    "name": "Raboot",
    "national_id": 814,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 190,
    "name": "Cinderace",
    "national_id": 815,
    "specialties": [
      "BurnHype",
      "Burn",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 191,
    "name": "Skwovet",
    "national_id": 819,
    "specialties": [
      "SearchHype",
      "Search",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 192,
    "name": "Greedent",
    "national_id": null,
    "specialties": [
      "Party",
      "Party"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 193,
    "name": "Rolycoly",
    "national_id": 837,
    "specialties": [
      "BurnGather",
      "Burn",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 194,
    "name": "Carkol",
    "national_id": 838,
    "specialties": [
      "BurnGather",
      "Burn",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 195,
    "name": "Coalossal",
    "national_id": 839,
    "specialties": [
      "BurnGather",
      "Burn",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 196,
    "name": "Toxel",
    "national_id": 848,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 197,
    "name": "Toxtricity Amped Form",
    "national_id": null,
    "specialties": [
      "GenerateHype",
      "Generate",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 197,
    "name": "Toxtricity Low Key Form",
    "national_id": null,
    "specialties": [
      "GenerateHype",
      "Generate",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 198,
    "name": "Fidough",
    "national_id": 926,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 199,
    "name": "Dachsbun",
    "national_id": 927,
    "specialties": [
      "SearchTrade",
      "Search",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 200,
    "name": "Charcadet",
    "national_id": 935,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 201,
    "name": "Armarouge",
    "national_id": 936,
    "specialties": [
      "BurnTrade",
      "Burn",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 202,
    "name": "Ceruledge",
    "national_id": 937,
    "specialties": [
      "BurnTrade",
      "Burn",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 203,
    "name": "Glimmet",
    "national_id": 969,
    "specialties": [
      "Litter",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 204,
    "name": "Glimmora",
    "national_id": 970,
    "specialties": [
      "Litter",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 205,
    "name": "Gimmighoul",
    "national_id": 999,
    "specialties": [
      "Collect",
      "Collect"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 206,
    "name": "Gholdengo",
    "national_id": 1000,
    "specialties": [
      "Collect",
      "Collect"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 207,
    "name": "Vulpix",
    "national_id": 37,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 208,
    "name": "Ninetales",
    "national_id": 38,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 209,
    "name": "Poliwag",
    "national_id": 60,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 210,
    "name": "Poliwhirl",
    "national_id": 61,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 211,
    "name": "Poliwrath",
    "national_id": 62,
    "specialties": [
      "WaterBuild",
      "Water",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 212,
    "name": "Politoed",
    "national_id": 186,
    "specialties": [
      "WaterHype",
      "Water",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 213,
    "name": "Abra",
    "national_id": 63,
    "specialties": [
      "Teleport",
      "Teleport"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 214,
    "name": "Kadabra",
    "national_id": 64,
    "specialties": [
      "Teleport",
      "Teleport"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 215,
    "name": "Alakazam",
    "national_id": 65,
    "specialties": [
      "TeleportTrade",
      "Teleport",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 216,
    "name": "Mime Jr.",
    "national_id": 439,
    "specialties": [
      "Gather",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 217,
    "name": "Mr. Mime",
    "national_id": 122,
    "specialties": [
      "GatherBuild",
      "Gather",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 218,
    "name": "Porygon",
    "national_id": 137,
    "specialties": [
      "Recycle",
      "Recycle"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 219,
    "name": "Porygon2",
    "national_id": 233,
    "specialties": [
      "Recycle",
      "Recycle"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 220,
    "name": "Porygon-Z",
    "national_id": 474,
    "specialties": [
      "Rarify",
      "Rarify"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 221,
    "name": "Dratini",
    "national_id": 147,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 222,
    "name": "Dragonair",
    "national_id": 148,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 223,
    "name": "Dragonite",
    "national_id": 149,
    "specialties": [
      "WaterFly",
      "Water",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 224,
    "name": "Cyndaquil",
    "national_id": 155,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 225,
    "name": "Quilava",
    "national_id": 156,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 226,
    "name": "Typhlosion",
    "national_id": 157,
    "specialties": [
      "BurnTrade",
      "Burn",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 227,
    "name": "Misdreavus",
    "national_id": 200,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 228,
    "name": "Mismagius",
    "national_id": 429,
    "specialties": [
      "GatherTrade",
      "Gather",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 229,
    "name": "Girafarig",
    "national_id": 203,
    "specialties": [
      "Gather",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 230,
    "name": "Farigiraf",
    "national_id": 981,
    "specialties": [
      "GatherSearch",
      "Gather",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 231,
    "name": "Ralts",
    "national_id": 280,
    "specialties": [
      "Teleport",
      "Teleport"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 232,
    "name": "Kirlia",
    "national_id": 281,
    "specialties": [
      "Teleport",
      "Teleport"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 233,
    "name": "Gardevoir",
    "national_id": 282,
    "specialties": [
      "TeleportTrade",
      "Teleport",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 234,
    "name": "Gallade",
    "national_id": 475,
    "specialties": [
      "TeleportBuild",
      "Teleport",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 235,
    "name": "Plusle",
    "national_id": 311,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 236,
    "name": "Minun",
    "national_id": 312,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 237,
    "name": "Trapinch",
    "national_id": 328,
    "specialties": [
      "BulldozeLitter",
      "Bulldoze",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 238,
    "name": "Vibrava",
    "national_id": 329,
    "specialties": [
      "BulldozeFly",
      "Bulldoze",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 239,
    "name": "Flygon",
    "national_id": 330,
    "specialties": [
      "BulldozeFly",
      "Bulldoze",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 240,
    "name": "Swablu",
    "national_id": 333,
    "specialties": [
      "Litter",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 241,
    "name": "Altaria",
    "national_id": 334,
    "specialties": [
      "LitterFly",
      "Litter",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 242,
    "name": "Duskull",
    "national_id": 355,
    "specialties": [
      "Gather",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 243,
    "name": "Dusclops",
    "national_id": 356,
    "specialties": [
      "Gather",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 244,
    "name": "Dusknoir",
    "national_id": 477,
    "specialties": [
      "GatherTrade",
      "Gather",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 245,
    "name": "Beldum",
    "national_id": 374,
    "specialties": [
      "Recycle",
      "Recycle"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 246,
    "name": "Metang",
    "national_id": 375,
    "specialties": [
      "Recycle",
      "Recycle"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 247,
    "name": "Metagross",
    "national_id": 376,
    "specialties": [
      "RecycleCrush",
      "Recycle",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 248,
    "name": "Snivy",
    "national_id": 495,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 249,
    "name": "Servine",
    "national_id": 496,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 250,
    "name": "Serperior",
    "national_id": 497,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 251,
    "name": "Froakie",
    "national_id": 656,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 252,
    "name": "Frogadier",
    "national_id": 657,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 253,
    "name": "Greninja",
    "national_id": 658,
    "specialties": [
      "WaterChop",
      "Water",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 254,
    "name": "Dedenne",
    "national_id": 702,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 255,
    "name": "Noibat",
    "national_id": 714,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 256,
    "name": "Noivern",
    "national_id": 715,
    "specialties": [
      "SearchFly",
      "Search",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 257,
    "name": "Rookidee",
    "national_id": 821,
    "specialties": [
      "Chop",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 258,
    "name": "Corvisquire",
    "national_id": 822,
    "specialties": [
      "Chop",
      "Chop"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 259,
    "name": "Corviknight",
    "national_id": 823,
    "specialties": [
      "ChopFly",
      "Chop",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 260,
    "name": "Dreepy",
    "national_id": 885,
    "specialties": [
      "GatherSearch",
      "Gather",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 261,
    "name": "Drakloak",
    "national_id": 886,
    "specialties": [
      "GatherSearch",
      "Gather",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 262,
    "name": "Dragapult",
    "national_id": 887,
    "specialties": [
      "GatherTrade",
      "Gather",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 263,
    "name": "Sprigatito",
    "national_id": 906,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 264,
    "name": "Floragato",
    "national_id": 907,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 265,
    "name": "Meowscarada",
    "national_id": 908,
    "specialties": [
      "GrowHype",
      "Grow",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 266,
    "name": "Wattrel",
    "national_id": 940,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 267,
    "name": "Kilowattrel",
    "national_id": 941,
    "specialties": [
      "GenerateFly",
      "Generate",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 268,
    "name": "Tinkatink",
    "national_id": 957,
    "specialties": [
      "Build",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 269,
    "name": "Tinkatuff",
    "national_id": 958,
    "specialties": [
      "Build",
      "Build"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 270,
    "name": "Tinkaton",
    "national_id": null,
    "specialties": [
      "Engineer",
      "Engineer"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 271,
    "name": "Aerodactyl",
    "national_id": 142,
    "specialties": [
      "Fly",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 272,
    "name": "Cranidos",
    "national_id": 408,
    "specialties": [
      "Crush",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 273,
    "name": "Rampardos",
    "national_id": 409,
    "specialties": [
      "CrushLitter",
      "Crush",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 274,
    "name": "Shieldon",
    "national_id": 410,
    "specialties": [
      "Crush",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 275,
    "name": "Bastiodon",
    "national_id": 411,
    "specialties": [
      "CrushLitter",
      "Crush",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 276,
    "name": "Tyrunt",
    "national_id": 696,
    "specialties": [
      "Crush",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 277,
    "name": "Tyrantrum",
    "national_id": 697,
    "specialties": [
      "CrushLitter",
      "Crush",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 278,
    "name": "Amaura",
    "national_id": 698,
    "specialties": [
      "Crush",
      "Crush"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 279,
    "name": "Aurorus",
    "national_id": 699,
    "specialties": [
      "CrushLitter",
      "Crush",
      "Litter"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 280,
    "name": "Eevee",
    "national_id": 133,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 281,
    "name": "Vaporeon",
    "national_id": 134,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 282,
    "name": "Jolteon",
    "national_id": 135,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 283,
    "name": "Flareon",
    "national_id": 136,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 284,
    "name": "Espeon",
    "national_id": 196,
    "specialties": [
      "Gather",
      "Gather"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 285,
    "name": "Umbreon",
    "national_id": 197,
    "specialties": [
      "Search",
      "Search"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 286,
    "name": "Leafeon",
    "national_id": 470,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 287,
    "name": "Glaceon",
    "national_id": 471,
    "specialties": [
      "Trade",
      "Trade"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 288,
    "name": "Sylveon",
    "national_id": 700,
    "specialties": [
      "Hype",
      "Hype"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 289,
    "name": "Kyogre",
    "national_id": 382,
    "specialties": [
      "???",
      "???"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 290,
    "name": "Raikou",
    "national_id": 243,
    "specialties": [
      "Generate",
      "Generate"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 291,
    "name": "Entei",
    "national_id": 244,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 292,
    "name": "Suicune",
    "national_id": 245,
    "specialties": [
      "Water",
      "Water"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 293,
    "name": "Volcanion",
    "national_id": 721,
    "specialties": [
      "Burn",
      "Burn"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 294,
    "name": "Articuno",
    "national_id": 144,
    "specialties": [
      "Fly",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 295,
    "name": "Zapdos",
    "national_id": 145,
    "specialties": [
      "Fly",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 296,
    "name": "Moltres",
    "national_id": 146,
    "specialties": [
      "Fly",
      "Fly"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 297,
    "name": "Lugia",
    "national_id": 249,
    "specialties": [
      "???",
      "???"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 298,
    "name": "Ho-Oh",
    "national_id": 250,
    "specialties": [
      "???",
      "???"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 299,
    "name": "Mewtwo",
    "national_id": 150,
    "specialties": [
      "Teleport",
      "Teleport"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 300,
    "name": "Mew",
    "national_id": 151,
    "specialties": [
      "Teleport",
      "Teleport"
    ],
    "source": "main"
  },
  {
    "pokopia_num": 1,
    "name": "Hoppip",
    "national_id": 187,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "event"
  },
  {
    "pokopia_num": 2,
    "name": "Skiploom",
    "national_id": 188,
    "specialties": [
      "Grow",
      "Grow"
    ],
    "source": "event"
  },
  {
    "pokopia_num": 3,
    "name": "Jumpluff",
    "national_id": 189,
    "specialties": [
      "GrowLitter",
      "Grow",
      "Litter"
    ],
    "source": "event"
  }
]
